version: "3.7"
services:
  web:
    build: .
    depends_on:
      - redis
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./src
        target: /app
  redis:
    image: redis
    volumes:
      - type: bind
        source: ./redis
        target: /data